bpmn-io/dmn-js

docs/project/SETUP.md

With the old url, you get a big red 404 ;)

Typo npm-docs-link

---

styles/dmn-clausevalues-setter.less
styles/dmn-string-editor.less

this commit adds a fixed maximum height of 108 px (enough space for 5 items with drawn checks or 6 items with checkboxes) to the lists in the context-menu when adding and selecting input values and allowed values.
closes #209

fix(dmn-js): make context-menu lists scrollable

---

packages/dmn-js-drd/assets/css/dmn-js-drd.css
packages/dmn-js-drd/lib/Viewer.js
packages/dmn-js-drd/lib/features/definition-properties/PaletteAdapter.js
packages/dmn-js-drd/lib/features/definition-properties/modeler.js
packages/dmn-js-drd/lib/features/definition-properties/viewer.js
packages/dmn-js-drd/test/spec/features/definition-properties/DefinitionPropertiesSpec.js

Building on top of https://github.com/bpmn-io/diagram-js/issues/199, this makes decision detail box in DRD view responsive:
* triggers resize on attachTo
* shows detail box at correct position with palette, palette two column and without

DRD: Make Decision detail box responsive 

---

packages/dmn-js-shared/src/base/Manager.js
packages/dmn-js-shared/test/spec/base/ManagerSpec.js
packages/dmn-js/CHANGELOG.md

This adds the life-cycle events for XML export as provided by bpmn-js, too.

feat(shared): emit saveXML life-cycle events

---

packages/dmn-js-decision-table/package.json
packages/dmn-js-decision-table/src/features/decision-table-properties/components/DecisionTablePropertiesEditorComponent.js
packages/dmn-js-decision-table/test/spec/features/decision-table-properties/DecisionTablePropertiesEditorSpec.js
packages/dmn-js-literal-expression/src/Viewer.js
packages/dmn-js-literal-expression/src/core/ElementRegistry.js
packages/dmn-js-literal-expression/src/core/index.js
packages/dmn-js-literal-expression/src/features/decision-properties/components/DecisionPropertiesComponent.js
packages/dmn-js-literal-expression/src/features/decision-properties/components/DecisionPropertiesEditorComponent.js
packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesComponent.js
packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js
packages/dmn-js-literal-expression/src/features/modeling/Modeling.js
packages/dmn-js-literal-expression/src/features/textarea/components/TextareaComponent.js
packages/dmn-js-literal-expression/src/features/textarea/components/TextareaEditorComponent.js
packages/dmn-js-literal-expression/src/features/view-drd/ViewDrd.js
packages/dmn-js-literal-expression/test/spec/ViewerSpec.js
packages/dmn-js-literal-expression/test/spec/core/ElementRegistrySpec.js
packages/dmn-js-literal-expression/test/spec/features/decision-properties/DecisionPropertiesEditorSpec.js
packages/dmn-js-literal-expression/test/spec/features/decision-properties/DecisionPropertiesSpec.js
packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionEditorPropertiesSpec.js
packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionPropertiesSpec.js
packages/dmn-js-literal-expression/test/spec/features/modeling/ModelingSpec.js
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaSpec.js
packages/dmn-js-shared/package.json
packages/dmn-js-shared/src/base/viewer/Viewer.js
packages/dmn-js-shared/src/base/viewer/core/ChangeSupport.js
packages/dmn-js-shared/src/features/modeling/cmd/UpdatePropertiesHandler.js
packages/dmn-js-shared/test/spec/base/viewer/TestHelper.js
packages/dmn-js-shared/test/spec/base/viewer/core/ChangeSupportSpec.js

* add ElementRegistry#updateId method
* UpdatePropertiesHandler calls ElementRegistry#updateId when ID is changing
* ChangeSupport listens for 'element.updateId' event fired by ElementRegistry
* add ElementRegistry to dmn-js-literal-expression to enable ChangeSupport update
Depends on https://github.com/bpmn-io/table-js/issues/19
Closes #367

fix(change-support): update change support on ID update

---

packages/dmn-js-shared/src/base/Manager.js
packages/dmn-js-shared/test/spec/base/ManagerSpec.js

Viewers of each dmn-js library fire attach event
when they are attached to a container. The same is
the case regarding other libraries from the modelling
family, i.e. bpmn-js and cmmn-js. Thus, the change
is rather a fix than a feature since user expects
such event to be fired.

fix(shared/Manager): fire attach event in attachTo

---

packages/dmn-js-shared/src/base/Manager.js
packages/dmn-js-shared/test/spec/base/ManagerSpec.js
packages/dmn-js/CHANGELOG.md

This adds the `detach` event, mirroring https://github.com/bpmn-io/dmn-js/pull/386.

chore(shared/Manager): emit detach event

---

package-lock.json
packages/dmn-js-decision-table/package.json
packages/dmn-js-drd/package.json
packages/dmn-js-drd/src/features/modeling/DrdUpdater.js
packages/dmn-js-drd/test/fixtures/dmn/reconnect.dmn
packages/dmn-js-drd/test/spec/features/modeling/DrdUpdaterSpec.js
packages/dmn-js-literal-expression/package.json
packages/dmn-js-shared/package.json
packages/dmn-js/package.json

Requires https://github.com/bpmn-io/diagram-js/pull/317

fix(drd/DrdUpdater): do not crop connections straight after reconnection

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css

Closes #404
Preview (`#f8f8f8`): 
Alternatively, `#eeeeee`:
The color can be easily changed. I am open for suggestions.

Add background color to even table rows

---

packages/dmn-js-shared/karma.base.js

This adds source maps to the dev mode. It does not affect the production
code, but makes debugging the tests much easier. The most demanding
devtool was chosen because it's the most useful and still does not seem
to reduce the performance in any significant way.

Use source maps in dev

---

packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCellContextMenu.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputCellContextMenu.js
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/DecisionTableHeadEditorSpec.js

This fixes a problem of restoring the persisted value when
user erased the text. The unsaved `undefined` value was ignored
as falsy and then the persisted value was inserted into the input.
Related to https://github.com/camunda/camunda-modeler/issues/826

fix(decision-table-head): correctly handle values erasing

---

packages/dmn-js-decision-table/package.json
packages/dmn-js-decision-table/test/spec/features/hit-policy/HitPolicyEditingSpec.js
packages/dmn-js-shared/src/components/InputSelect.js
packages/dmn-js-shared/test/spec/components/InputSelectSpec.js

This prevents closing context menu when option is selected. 
Closes #421 
Contains https://github.com/bpmn-io/dmn-js/pull/422

fix(shared/InputSelect): suppress mousedown event on select

---

packages/dmn-js-decision-table/src/features/hit-policy/editor/components/HitPolicyCellContextMenu.js
packages/dmn-js-decision-table/test/spec/features/hit-policy/HitPolicyEditingSpec.js
packages/dmn-js-shared/test/util/EventUtil.js

Allow to clear aggregation from dropdown

---

packages/dmn-js-drd/src/features/palette/PaletteProvider.js
packages/dmn-js-drd/test/spec/features/palette/PaletteProviderSpec.js

This adds missing titles for palette entries. The naming is based on the way we do it in `bpmn-js`. I think it's worth it to merge this as therefore the users have actually an opportunity to learn the elements' names.

Provide titles for all entries

---

packages/dmn-js-decision-table/src/Editor.js
packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js
packages/dmn-js-decision-table/src/features/decision-rules/index.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCell.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCellContextMenu.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/index.js
packages/dmn-js-decision-table/src/features/expression-language/ExpressionLanguage.js
packages/dmn-js-decision-table/src/features/expression-language/index.js
packages/dmn-js-decision-table/src/features/simple-mode/components/SimpleModeButtonComponent.js
packages/dmn-js-decision-table/src/features/simple-mode/index.js
packages/dmn-js-decision-table/test/spec/expression-language.dmn
packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesEditorSpec.js
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorCellSpec.js
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorSpec.js
packages/dmn-js-literal-expression/src/Editor.js
packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js
packages/dmn-js-literal-expression/src/features/literal-expression-properties/index.js
packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionEditorPropertiesSpec.js
packages/dmn-js-shared/src/features/expression-languages/ExpressionLanguages.js
packages/dmn-js-shared/src/features/expression-languages/index.js
packages/dmn-js-shared/test/spec/features/expression-languages/ExpressionLanguagesSpec.js

This adds `ExpressionLanguages` module which reads the config
in order to provide available expression language options
as well as defaults for the editor and selected components.
Closes #433

Make expression languages configurable

---

packages/dmn-js-drd/src/Modeler.js
packages/dmn-js-drd/src/features/distribute-elements/DrdDistributeElements.js
packages/dmn-js-drd/src/features/distribute-elements/index.js
packages/dmn-js-drd/test/spec/ModelerSpec.js

Add aligment, distribution and modeling helpers known and loved in bpmn-js:
* snapping
* grid snapping
* keyboard move
* align / distrbute
* automatic canvas movement
__In action__

DRD: Add basic diagram-js modeling helpers

---

packages/dmn-js-drd/src/features/distribute-elements/DrdDistributeElements.js
packages/dmn-js-drd/test/spec/features/distribute-elements/DrdDistributeElements.dmn
packages/dmn-js-drd/test/spec/features/distribute-elements/DrdDistributeElementsSpec.js

This PR enables proper element distribution in DRD diagrams.
Distribution is not blind to existing element aligments. If it finds certain axis it will group elements so that they are on the same axis (as seen in the screenshots below). So in this sense, it automatically generates levels as prototyped in https://github.com/bpmn-io/dmn-js/issues/450.
Also as seen in the screenshots below, we may want to invest some more time to properly fix connection layouts after distribution took place. I consider this a future improvement.
__Input__
__Distribute Horizontally__
__Distribute Vertically__

Enable element distribution

---

.travis.yml

Closes #459
We can still install alphas manually.

Update examples and websites on stable release only

---

packages/dmn-js-decision-table/src/features/allowed-values/behavior/AllowedValuesUpdateBehavior.js
packages/dmn-js-decision-table/src/features/modeling/Modeling.js
packages/dmn-js-literal-expression/src/features/modeling/Modeling.js
packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js

This ensures consistency between dmn-js-drd and remaining packages. Previously, the packages executed differently named commands for the same feature. This led to [a workaround in `dmn-js-properties-panel`](https://github.com/bpmn-io/dmn-js-properties-panel/blob/70bc931c4a570dd5e1ede42dd275ce19b38485af/lib/adapter/decision-table/DecisionTableAdapter.js#L37). If we merge this change, we can get rid of the workarounds. Also, fix for https://github.com/camunda/camunda-modeler/issues/1679 will not require a workaround in the [`IdChangeBehavior`](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js#L14).
BTW, we use `element.updateProperties` [in `bpmn-js` too.](https://github.com/bpmn-io/bpmn-js/blob/0c0ebea49f8b20e317ca28b157 …

Rename `updateProperties` to `element.updateProperties`

---

packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js
packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesEditorSpec.js
packages/dmn-js-decision-table/test/spec/features/decision-rules/empty-rule.dmn
packages/dmn-js-shared/src/components/EditableComponent.js
packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js

This removes the missleading output placeholder `-` from the decision table.
Related to https://github.com/camunda/camunda-modeler/issues/1677

No output placeholder 7.x

---

packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js
packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesEditorSpec.js
packages/dmn-js-decision-table/test/spec/features/decision-rules/empty-rule.dmn
packages/dmn-js-shared/src/components/EditableComponent.js
packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js

This removes the missleading output placeholder `-` from the decision table.
Port of https://github.com/bpmn-io/dmn-js/pull/472 to `develop`.
Related to https://github.com/camunda/camunda-modeler/issues/1677

No output placeholder 8.x

---

packages/dmn-js-shared/src/features/expression-languages/ExpressionLanguages.js

`Array.prototype.find` is not polyfilled within current
babel config. This caused problem with IE11 where
the function is not implemented.
For more context, before this commit the PhantomJS tests for the properties panel used to fail because of lacking `find`.

chore(expression-languages): use min-dash find

---

packages/dmn-js-drd/src/features/label-editing/LabelEditingProvider.js
packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js

Closes #185
⬇️🦥🍏
With #481 implemented, this will even work nicer.

feat(drd): activate direct editing after text annotation create

---

packages/dmn-js-decision-table/test/spec/expression-language.dmn
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorCellSpec.js
packages/dmn-js-shared/src/features/expression-languages/ExpressionLanguages.js
packages/dmn-js-shared/test/spec/features/expression-languages/ExpressionLanguagesSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/1710

Set FEEL as default expression language

---

packages/dmn-js-decision-table/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js
packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js

Related to camunda/camunda-modeler#1796
Fixes a bug only existing in old v7 version of the library
--------
_Solution Sketch_
The error basically exists because we have to deal with two updating properties events, which is also explained here: https://github.com/camunda/camunda-modeler/issues/1769#issuecomment-614030674
* `updateProperties`
* `elementProperties`
Basically it crashes because the properties panel executes the `element.updateProperties` event, which `dmn-js-decision-table` does not have a handler for. That's why the IdChangeBehavior is executed without `oldProperties` is populated. This got fixed in v8.
However, to backport this fix we can not easily add a temporary `element.updateProperties` handler to the decision table module, because we adding this one in the properties …

Prevent updating id if no oldProperties available

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
packages/dmn-js-decision-table/src/features/hit-policy/components/HitPolicy.js

After the hit policy PR was merged, I noticed that in the viewer it looks kinda odd. This PR is aimed to fix the problem.
Before:
After:

chore(hit-policy): improve viewer style

---

packages/dmn-js-shared/src/base/Manager.js

This prevents import error in TypeScript environment.
Closes #517

chore(shared/Manager): add extension to camunda moddle import

---

packages/dmn-js-drd/src/features/rules/DrdRules.js
packages/dmn-js-drd/test/spec/features/rules/DrdRulesSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/1817
Related to https://github.com/camunda/camunda-modeler/issues/1702
Related to https://github.com/camunda/camunda-modeler/issues/1763

fix(drd/drd-rules): allow association regardless of connection direction

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css

Adjust the appearance of the add column button
* circular clickable area
* button centered
* white circular outline
Related to https://github.com/bpmn-io/dmn-js/pull/511

chore(decision-table): adjust add column button appearance

---

packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCellContextMenu.js
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorCellSpec.js

This popped up on Slack as part of general feedback. The PR makes sure that we display default expression language (FEEL) when none is set.

feat(decision-table/head): display FEEL as default expression language

---

packages/dmn-js-decision-table/src/features/decision-table-head/editor/InputEditingProvider.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/OutputEditingProvider.js

Related to https://github.com/camunda/camunda-modeler/issues/1869

Open input/output editing at correct position

---

packages/dmn-js-shared/src/components/InputSelect.js
packages/dmn-js-shared/test/spec/components/InputSelectSpec.js

Hide InputSelect options on global mousedown event

---

packages/dmn-js-decision-table/src/features/copy-cut-paste/CopyCutPaste.js
packages/dmn-js-decision-table/test/spec/features/copy-cut-paste/CopyCutPasteSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/1246
This is not an exact solution to the problem however Volker and I decided that it's good enough for now until we put some effort on implementing the native clipboard and deprecating the internal clipboard for good.

Clear clipboard after pasting

---

packages/dmn-js-shared/assets/css/dmn-js-shared.css
packages/dmn-js-shared/src/components/InputSelect.js
packages/dmn-js-shared/test/spec/components/InputSelectSpec.js

Previously, options were positioned using `position: fixed`.
However, this can lead to bugs as element can be positioned thus
either relatively to the viewport (intended) or some other container
in which dmn-js is rendered. The latter happens if container
has `transform`, `filter` or `perspective` set to other value
than `none`. This is exactly what we use in order to display
bpmn.io logo all the time in correct place of decision table
and literal expression views.
Cf. https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed
Closes #589

Use absolute position for InputSelect options

---

packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesEditorSpec.js

These tests only work once in a while.
We cannot have a sporadically failing test suite.
Closes https://github.com/bpmn-io/dmn-js/issues/618

test: disable focus tests on Firefox

---

packages/dmn-js-drd/src/features/modeling/DrdUpdater.js
packages/dmn-js-drd/test/spec/features/modeling/DrdUpdaterSpec.js
packages/dmn-js-drd/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js
packages/dmn-js-drd/test/spec/features/modeling/behavior/replace-element-behavior.dmn

The issue is that when replacing the decision the association's parent from the model's perspective is changed to the text annotation. In the case of information requirements and such the parent is indeed the target element. Not in this case since the association is an artifact.
This issue was fixed before (https://github.com/bpmn-io/dmn-js/commit/90a7952153d3bfc87ddd6e5ec75b167326d6d231#diff-a42b136569b62592b63126d0bfe523df9cfd77884dfd10741252ceead428e185R265) but then broken again (https://github.com/bpmn-io/dmn-js/commit/853eea1146af68ba18f6b2e8d74dbf3446c5c7a0#).
So we're fixing it again. ♻️ 
Related to camunda/camunda-modeler#1763
Related to camunda/camunda-modeler#1814
Related to camunda/camunda-modeler#1874
Related to https://github.com/camunda/camunda-modeler/issues/2052

Fix Association Parent Update (Again)

---

packages/dmn-js-drd/src/features/context-pad/ContextPadProvider.js
packages/dmn-js-drd/test/spec/features/context-pad/ContextPadProviderSpec.js

related to https://github.com/camunda/camunda-modeler/issues/2042
Modified :
- ContextPadProvider.js for enabling connect tool for text annotation.
- ContextPadProviderSpec.js for tests.
- for tooltip text i put : "Connect using association" when mouse hover the connect tool

feat(connect-tool) : enable for text annotation

---

packages/dmn-js-decision-table/src/features/editor-actions/DecisionTableEditorActions.js
packages/dmn-js-decision-table/test/spec/features/editor-actions/EditorActionsSpec.js

Previously the editor would fail to add an output if no input was given in the DMN table. This PR fixes the behavior.

Allow to add output if dmn:input does not exist

---

packages/dmn-js-shared/src/base/Manager.js
packages/dmn-js-shared/test/spec/base/ManagerSpec.js

I spotted this missing testcoverage and inconsistency in the event lifecycle and wanted to clean it up prior to finishing the dmn-js promisification. This allows me to have a stable baseline for the promisification exercise.

Correct import xml event lifecycle

---

packages/dmn-js-decision-table/src/Viewer.js
packages/dmn-js-drd/src/Viewer.js
packages/dmn-js-literal-expression/src/Viewer.js
packages/dmn-js/CHANGELOG.md

Correct inter-package imports (same way we already do it, for example [here](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-decision-table/src/Editor.js#L15))

fix: correct inter-package imports

---

packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js

Since this is a default export, it is not so important what the class is called here. However, for consistency and maintainability reasons, I would suggest naming this class also as it is called in the other components. In addition, it then corresponds to the file name.

refactor(dmn-js-decision-table): rename class

---

packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesEditorSpec.js
packages/dmn-js-decision-table/test/spec/features/expression-language/ExpressionLanguageSpec.js
packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionEditorPropertiesSpec.js
packages/dmn-js-shared/src/features/expression-languages/ExpressionLanguages.js
packages/dmn-js-shared/test/spec/features/expression-languages/ExpressionLanguagesSpec.js

Closes #675
BREAKING CHANGES:
* The only expression language selectable per default is FEEL.
To change the list, pass respective ELs via `expressionLanguages`
configuration.

feat: remove Camunda Platform expression languages

---

package-lock.json
packages/dmn-js-shared/package-lock.json
packages/dmn-js-shared/package.json
packages/dmn-js-shared/src/base/Manager.js

This is to make sure we don't depend on vendor extension.
Closes #682
Closes #673
BREAKING CHANGES:
* `camunda` namespace moddle extension is no longer part of the package.
Consider using [camunda/camunda-dmn-js](https://github.com/camunda/camunda-dmn-js) to support Camunda Platform.
---
Built on top of https://github.com/bpmn-io/dmn-js/pull/681

Drop `camunda-dmn-moddle` dependency

---

packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCellContextMenu.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js
packages/dmn-js-decision-table/src/features/expression-language/ExpressionLanguage.js
packages/dmn-js-decision-table/test/spec/expression-language.dmn
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorCellSpec.js
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorSpec.js
packages/dmn-js-decision-table/test/spec/features/expression-language/ExpressionLanguageSpec.js
packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js
packages/dmn-js-literal-expression/test/spec/expression-language.dmn
packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionEditorPropertiesSpec.js

EL select is displayed for two cases:
* the configured EL is not the default one
* there are multiple ELs available
Closes #686

Display EL select only when necessary

---

packages/dmn-js-decision-table/src/features/simple-mode/components/SimpleModeButtonComponent.js

Closes https://github.com/bpmn-io/dmn-js/issues/668
This was a small oversight to apply the debounced hide then show even when the button was already hidden to start with.

fix: edit button no longer always shows on scroll in decision table

---

packages/dmn-js-drd/src/draw/DrdRenderer.js
packages/dmn-js-drd/test/spec/draw/DrdRendererSpec.js

`#000000` changed to `hsl(225, 10%, 15%)` according to [571](https://github.com/bpmn-io/diagram-js/issues/571).
---
Related to https://github.com/bpmn-io/diagram-js/issues/571

feat: change default black to off black

---

babel.config.json
packages/dmn-js-decision-table/.babelrc
packages/dmn-js-drd/.babelrc
packages/dmn-js-literal-expression/.babelrc
packages/dmn-js-shared/.babelrc
packages/dmn-js/.babelrc
packages/dmn-js/CHANGELOG.md

* Migrated to ES2018 syntax. [Read the blog post with details and a migration guide](https://bpmn.io/blog/posts/2022-core-libraries-migrated-to-es2018.html).
---
Requires https://github.com/bpmn-io/bpmn.io/pull/147

feat: transpile to ES2018

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
packages/dmn-js-decision-table/src/features/decision-table-head/components/DecisionTableHead.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCell.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputCell.js

- show the label as `title` so hover always shows complete label
- break label up to 3 lines
- Use ellipses afterwards to prevent super long labels or expressions of taking up the whole screen
Note: I used `-webkit-line-clamp` for multi-line ellipsis. This is supported in all major browsers (except IE, cf. https://caniuse.com/css-line-clamp)

feat: break long expression names

---

packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesComponent.js

Closes https://github.com/camunda/web-modeler/issues/4252
There are situations when the `typeRef` related to a Literal Expression is just undefined. In these situations an error is thrown:
```
react_devtools_backend.js:2655 unhandled error in event listener TypeError: Cannot read properties of undefined (reading 'replace')
at LiteralExpressionPropertiesComponent.translate [as _translate] (translate.js?e4f0:27:1)
at LiteralExpressionPropertiesComponent.render (LiteralExpressionPropertiesComponent.js?7b38:13:415)
```
With the proposed change, the `translate` function would return `undefined` (instead of blocking with an error), so the hyphen will be shown for this particular "Variable Type":

fix(literal-expression): avoid translate to fail with undefined typeRef

---

package-lock.json
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js
packages/dmn-js-decision-table/test/helper/index.js
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorCellSpec.js
packages/dmn-js-shared/package.json
packages/dmn-js-shared/src/components/LiteralExpression.js
packages/dmn-js-shared/test/spec/components/LiteralExpressionSpec.js

https://github.com/bpmn-io/dmn-js/assets/28307541/28344694-7044-4396-99dd-b2f761917b8a
Closes #768

Embed FEEL editor in input expression

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css
packages/dmn-js-decision-table/src/features/cell-selection/CellSelectionUtil.js
packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js
packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js
packages/dmn-js-decision-table/test/helper/index.js
packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesEditorSpec.js
packages/dmn-js-shared/src/components/EditableComponent.js
packages/dmn-js-shared/src/components/LiteralExpression.js
packages/dmn-js-shared/test/util/EditorUtil.js

Embed FEEL editor in table cell

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
packages/dmn-js/CHANGELOG.md

Related to https://github.com/camunda/camunda-modeler/pull/3881#issuecomment-1733249226
Learning: `transform`s break computed positions in autocomplete, so we should try to avoid it if possible.

fix: display FEEL autocomplete suggestions in correct position

---

packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css
packages/dmn-js-literal-expression/src/features/textarea/components/TextareaEditorComponent.js
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js

feat: use FEEL editor in literal expression

---

packages/dmn-js-literal-expression/src/features/textarea/components/TextareaEditorComponent.js
packages/dmn-js-literal-expression/test/helper/index.js
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js

This was caused by an API mismatch. `ContentEditable` and `LiteralExpression` accept `onInput` while `EditableComponent` expects `onChange`.
Closes #786

fix: make FEEL editor in literal expression save value

---

package-lock.json
packages/dmn-js-decision-table/package.json
packages/dmn-js-decision-table/src/Editor.js
packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCellContextMenu.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js
packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesEditorSpec.js
packages/dmn-js-decision-table/test/spec/features/decision-rules/empty-rule.dmn
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditor.dmn
packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorCellSpec.js
packages/dmn-js-literal-expression/package.json
packages/dmn-js-literal-expression/src/Editor.js
packages/dmn-js-literal-expression/src/features/textarea/components/TextareaEditorComponent.js
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js
packages/dmn-js-literal-expression/test/spec/literal-expression.dmn
packages/dmn-js-shared/src/components/LiteralExpression.js

https://github.com/bpmn-io/dmn-js/assets/28307541/aa4ec739-b576-4957-b54c-30d77d2265fa
Closes #785

Implement variable suggestions

---

packages/dmn-js-drd/src/NavigatedViewer.js
packages/dmn-js-drd/src/features/editor-actions/DrdEditorActions.js
packages/dmn-js-drd/src/features/keyboard/DrdKeyboardBindings.js
packages/dmn-js-drd/src/features/search/DmnSearchProvider.js
packages/dmn-js-drd/src/features/search/index.js
packages/dmn-js-drd/test/spec/ModelerSpec.js
packages/dmn-js-drd/test/spec/features/editor-actions/DrdEditorActionsSpec.js
packages/dmn-js-drd/test/spec/features/keyboard/DrdKeyboardBindingsSpec.js
packages/dmn-js-drd/test/spec/features/search/DmnSearchProviderSpec.js
packages/dmn-js-drd/test/spec/features/search/dmn-search.dmn

Related to https://github.com/camunda/camunda-modeler/issues/1478

feat(dmn-js-drd): implement search

---

packages/dmn-js-decision-table/src/features/add-rule/components/AddRuleFootComponent.js
packages/dmn-js-decision-table/src/features/drag-and-drop/DragAndDrop.js
packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js

Hello everyone. I'm not a JavaScript developer and this is my first time working with node.js. The changes in this pr pass `npm run all` and are visible in `npm run start:translate`. Please let me know if you see any issues.
---
Three dmn-js ui labels are not translatable. This pr makes them translatable. 
Closes #793
* Decision Editor
* "Add Rule"
* "Move rule"
* Literal Expression Editor
* "name"

fix: add missing translations

---

packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css

Closes #789
I also tested this in web modeler
https://github.com/bpmn-io/dmn-js/assets/25825387/fbf58d84-0837-4aad-86e1-112946292178

feat(literal-decision): autogrow textarea

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css
packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
packages/dmn-js-decision-table/src/features/add-input-output/components/AddInput.js
packages/dmn-js-decision-table/src/features/add-input-output/components/AddOutput.js
packages/dmn-js-decision-table/src/features/create-inputs/components/CreateInputHeaderCell.js

fix: make add column buttons focussable

---

package-lock.json
packages/dmn-js-literal-expression/package.json
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js

We can't reliably ensure that the autocompletion opens in tests, so this solution makes the test use a mock variable resolver instead.
Closes #873

test: use spy to check if variables were retrieved

---

packages/dmn-js-shared/src/components/LiteralExpression.js

Simple enough fix!
Closes #838

fix(shared): show FEEL expressions with line wrapping

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css
packages/dmn-js-decision-table/src/features/decision-table-head/editor/InputEditingProvider.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/OutputEditingProvider.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditButton.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputEditButton.js

Run `npx @bpmn-io/sr bpmn-io/dmn-js#845-edit-button-for-decision-table-head` to try this out locally.
The button is visually hidden unless focussed with keyboard.
Closes #845
https://github.com/bpmn-io/dmn-js/assets/28307541/87b0de58-5779-40a1-b436-09158ea2ff25

feat: add edit input/output button

---

packages/dmn-js-drd/src/features/modeling/Modeling.js
packages/dmn-js-drd/src/features/modeling/cmd/UpdateModdlePropertiesHandler.js
packages/dmn-js-drd/test/spec/features/modeling/UpdateModdleProperties.dmn
packages/dmn-js-drd/test/spec/features/modeling/UpdateModdlePropertiesSpec.js
packages/dmn-js/CHANGELOG.md

Adds `Modeling#updateModdleProperties` mirroring [bpmn-js](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/Modeling.js#L144).
This is needed in the context of https://github.com/camunda/product-hub/issues/435 as users need to be able add a version tag to a decision through the properties panel. Since the version tag is an extension element we need `updateModdleProperties`.

feat(drd): add `Modeling#updateModdleProperties`

---

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css

Fix for flashing edit button when adding a new column.
Related https://github.com/camunda/camunda-modeler/issues/4388
https://github.com/user-attachments/assets/259bc300-69e2-49cc-841c-0861e4a37a6d

fix: edit button does not flash when adding new column

---

packages/dmn-js-decision-table/src/features/modeling/index.js
packages/dmn-js-decision-table/test/spec/features/modeling/behavior/NameChangeBehaviorSpec.js
packages/dmn-js-decision-table/test/spec/features/modeling/behavior/name-change-behavior.dmn
packages/dmn-js-drd/src/features/modeling/behavior/index.js
packages/dmn-js-drd/src/features/modeling/cmd/UpdatePropertiesHandler.js
packages/dmn-js-drd/src/features/replace/DrdReplace.js
packages/dmn-js-drd/test/spec/features/modeling/behavior/NameChangeBehaviorSpec.js
packages/dmn-js-drd/test/spec/features/modeling/behavior/name-change-behavior.dmn
packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js
packages/dmn-js-literal-expression/src/features/modeling/Modeling.js
packages/dmn-js-literal-expression/src/features/modeling/index.js
packages/dmn-js-literal-expression/test/spec/features/modeling/behavior/NameChangeBehaviorSpec.js
packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js
packages/dmn-js/CHANGELOG.md

fix: variable name changes when element name/label changes

---

packages/dmn-js-boxed-expression/assets/css/dmn-js-boxed-expression.css

Related to https://github.com/camunda/camunda-modeler/issues/4545
Follow up for the same issue in the decision table: https://github.com/camunda/camunda-modeler/issues/4342
Literal expression editor in BKM now takes full parent height.
https://github.com/user-attachments/assets/f6cd2b7a-bb17-4ae4-a32e-412e8ebcca86

fix: fix literal expression editor hitbox in BKM

---

packages/dmn-js-shared/src/components/ContentEditable.js

This fixes a regression introduced via a6dfc16b9cd6ebf56da14b532ccca728550cb0d8.
The prior change switched to `onKeyDown`, which is an synthetic event handler that cannot prevent default (on global clicks).
What we need to prevent default (global) clicks is actual DOM event handling. Quoting from the Inferno documentation [1]:
> Lower case events will bypass Inferno's event system in favour of
> using the native event system supplied by the browser.
[1]: https://www.infernojs.org/docs/guides/event-handling
---
The fixed behavior can be inspected via `npm start`, using the Dish Decision `JavaScript` field, but also in the fact that the test suite passes (again):

Prevent global `keydown` event when `ContentEditable` handled `ENTER`

---

package-lock.json
packages/dmn-js-drd/package.json
packages/dmn-js-drd/test/spec/features/definition-properties/DefinitionPropertiesSpec.js
packages/dmn-js-literal-expression/package.json
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js

This attempts to fix the flaky test which has been causing build failures for a while, e.g. https://github.com/bpmn-io/dmn-js/actions/runs/11365121269/job/31612772137?pr=909

test: fix flaky test in literal expression

---

packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css
packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js

Related to https://github.com/camunda/camunda-modeler/issues/4550
Add explicit styles for the table and make them into a class to prevent being overridden.
Possible a topic for further discussion as described here: https://github.com/bpmn-io/variable-outline/issues/4

fix: make literal expression variables table styles explicit

---

package.json

Make `dmn-js-builder` more explicit about not being something we want to release to public. If _somebody_ tries to release with `np` there should be some good indication that this is not what they actually desire to do:

chore: make dmn-js-builder more explicit

---

packages/dmn-js-drd/test/spec/features/modeling/behavior/NameChangeBehaviorSpec.js
packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js

https://github.com/user-attachments/assets/73f5fbd9-1ead-4cbb-81fd-8c2dcc6644c1
We've tested the label update but not the direct name change with `modeling.updateProperties`. Now we test for both.
Related to https://github.com/bpmn-io/dmn-js-properties-panel/issues/103 
Related to https://github.com/camunda/camunda-modeler/issues/4684

fix: make name change behavior not break on name change

---

packages/dmn-js-drd/test/spec/features/modeling/behavior/NameChangeBehaviorSpec.js
packages/dmn-js-shared/src/features/modeling/behavior/NameChangeBehavior.js
packages/dmn-js/CHANGELOG.md

This ports https://github.com/bpmn-io/dmn-js/pull/917 to `main` so that we can release v17.0.1 too.

Port #917 to `main`

---

packages/dmn-js-boxed-expression/src/features/function-definition/components/FunctionDefinitionEditorComponent.js
packages/dmn-js-boxed-expression/test/spec/features/function-definition/FunctionDefinitionEditorSpec.js

Closes #896 
You can update the parameters and the variables will be available in real-time in literal expression.

Formal parameters sync with literal expression 

---

packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js
packages/dmn-js-decision-table/test/spec/features/copy-cut-paste/CopyCutPasteKeyBindingsSpec.js
packages/dmn-js-decision-table/test/spec/features/keyboard/KeyboardSpec.js
packages/dmn-js-literal-expression/src/features/keyboard/Keyboard.js
packages/dmn-js/CHANGELOG.md

Closes https://github.com/bpmn-io/dmn-js/issues/920
Adjust Keyboard modules in `dmn-js-decision-table` and `dmn-js-literal-expression` to follow new implicit keyboard binding behavior.
Change the test for keyboard binding to subscript onto events instead of directly checking internal property.

fix: port implicit keyboard binding over to decision editors

---

package-lock.json
packages/dmn-js-shared/package.json
packages/dmn-js/CHANGELOG.md

* updates `@bpmn-io/feel-editor` to v1.10.0 to suggest latest Camunda FEEL built-ins ([@bpmn-io/feel-editor#65](https://github.com/bpmn-io/feel-editor/pull/65)) 

Update FEEL editor

---

packages/dmn-js-drd/src/features/context-pad/ContextPadProvider.js
packages/dmn-js-drd/test/spec/features/context-pad/ContextPadProviderSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/4554
Adds ContextPad actions for multi selections. The only action added for now is the delete action. Selecting multiple shapes and deleting with keyboard also works.
https://github.com/user-attachments/assets/162a86f2-d71e-4e40-bb5b-d7046652cb2e

Add delete action for multi element context

---

eslint.config.mjs
packages/dmn-js-boxed-expression/src/Editor.js
packages/dmn-js-decision-table/src/Editor.js
packages/dmn-js-decision-table/src/features/context-menu/ContextMenu.js
packages/dmn-js-decision-table/src/features/decision-rules/components/DecisionRulesCellEditorComponent.js
packages/dmn-js-decision-table/src/features/decision-rules/index.js
packages/dmn-js-decision-table/src/features/decision-table-head/editor/index.js
packages/dmn-js-decision-table/src/features/simple-duration-edit/Utils.js
packages/dmn-js-decision-table/src/features/simple-number-edit/Utils.js
packages/dmn-js-decision-table/test/spec/features/simple-date-time-edit/SimpleDateTimeEditSpec.js
packages/dmn-js-decision-table/test/spec/features/simple-date-time-edit/UtilsSpec.js
packages/dmn-js-drd/src/Viewer.js
packages/dmn-js-drd/src/draw/PathMap.js
packages/dmn-js-literal-expression/src/Editor.js
packages/dmn-js-literal-expression/src/features/literal-expression-properties/editor.js
packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js
packages/dmn-js-shared/src/components/LiteralExpression.js
packages/dmn-js-shared/src/features/feel-language-context/FeelLanguageContext.js
packages/dmn-js-shared/src/features/feel-language-context/index.js
packages/dmn-js-shared/src/util/PoweredByUtil.js
packages/dmn-js-shared/test/spec/components/LiteralExpressionSpec.js

Related to https://github.com/camunda/camunda-modeler/issues/4809
Enable setting feelLanguageContext via config providers
Best tested toghether with https://github.com/camunda/camunda-dmn-js/pull/145 to see an effect. 
assuming a folder structure like this:
- `root/bpmn-io/dmn-js` #4809-adopt-camunda-parser-dialect
- `root/camunda/camunda-dmn-js` #4809-adopt-camunda-parser-dialect
```bash
cd ./camunda/camunda-dmn-js #only if your not already in there
npm link ../../bpmn-io/dmn-js/packages/dmn-js --save
npm link ../../bpmn-io/dmn-js/packages/dmn-js-boxed-expression --save
npm link ../../bpmn-io/dmn-js/packages/dmn-js-decision-table --save
npm link ../../bpmn-io/dmn-js/packages/dmn-js-drd --save
npm link ../../bpmn-io/dmn-js/packages/dmn-js-literal-expression --save
npm link …
```

Support configuring feel language context

---

.github/workflows/COMMENT_TARGETS_MAIN.yml

Related to bpmn-io/internal-docs#1206
Add a github action that adds a comment if the target branch of a PR is main, (we want to target develop by default).
See for example the comment in this PR. But in this case I actually want to target main directly

ci: add comment on PRs targeting main
