package.json, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/test/spec/features/annotations/AnnotationsEditorSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-head/DecisionTableHeadEditorSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-properties/DecisionTablePropertiesEditorSpec.js, packages/dmn-js-decision-table/test/spec/features/rules/RulesEditorSpec.js, packages/dmn-js-shared/lib/components/ContentEditable.js, packages/dmn-js-shared/lib/components/EditableComponent.js, packages/dmn-js-shared/package.json, packages/dmn-js-shared/test/spec/components/ContentEditableSpec.js, packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js
This should pretty much address #297.
Closes #297
=> 297 selection update

packages/dmn-js-decision-table/lib/features/decision-rules/components/DecisionRulesCellComponent.js, packages/dmn-js-decision-table/lib/features/decision-table-head/components/DecisionTableHead.js, packages/dmn-js-decision-table/test/spec/features/decision-rules/DecisionRulesSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-head/DecisionTableHeadSpec.js
This solves [issue #357 ](https://github.com/bpmn-io/dmn-js/issues/357).
=> feat(decision-table): add data attribute to header input and output cells

packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputEditor.js
Closes #346
Closes https://github.com/camunda/camunda-modeler/issues/1247
=> feat(decision-table): show input and output label first in editors

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
=> fix(decision-table): fix layout bug for empty table on firefox

packages/dmn-js-decision-table/src/features/simple-mode/components/SimpleModeButtonComponent.js, packages/dmn-js-decision-table/test/spec/features/simple-mode/SimpleModeSpec.js
=> Display simple edit button when closed by clicking active cell

packages/dmn-js-decision-table/src/features/allowed-values/components/AllowedValuesEditing.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js, packages/dmn-js-decision-table/src/features/simple-date-edit/components/InputDateEdit.js, packages/dmn-js-decision-table/src/features/simple-date-edit/components/OutputDateEdit.js, packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css, packages/dmn-js-shared/assets/css/dmn-js-shared.css
=> Use button for buttons in hints

packages/dmn-js-drd/src/features/modeling/DrdUpdater.js, packages/dmn-js-drd/test/spec/features/modeling/DrdUpdaterSpec.js
Related to camunda/camunda-modeler#1606
=> fix(drd-updater): do not copy original to DI waypoint

packages/dmn-js-drd/src/features/rules/DrdRules.js, packages/dmn-js-drd/test/spec/features/rules/DrdRules.grouped.dmn, packages/dmn-js-drd/test/spec/features/rules/DrdRulesSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/1605
=> fix(drd/rules): allow connections to be moved with DMN elements

packages/dmn-js-drd/src/features/modeling/DrdUpdater.js, packages/dmn-js-drd/src/features/modeling/behavior/ReplaceConnectionBehavior.js, packages/dmn-js-drd/src/features/modeling/behavior/index.js, packages/dmn-js-drd/test/spec/features/modeling/DrdUpdaterSpec.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/replace-connection-behavior.dmn, packages/dmn-js-drd/test/spec/features/modeling/drd-updater.dmn
* do NOT move edges to text annotation targets
* replace connections on reconnect
Related to https://github.com/camunda/camunda-modeler/issues/1602
=> Replace Connection on Reconnect

packages/dmn-js-drd/src/features/context-pad/ContextPadProvider.js, packages/dmn-js-drd/src/features/modeling/DrdLayouter.js, packages/dmn-js-drd/test/spec/features/context-pad/ContextPadProviderSpec.js
+ test cover dat stuff
Related to https://github.com/camunda/camunda-modeler/issues/1604
=> fix(drd): correct append behavior

packages/dmn-js-decision-table/.npmignore, packages/dmn-js-drd/.npmignore, packages/dmn-js-literal-expression/.npmignore, packages/dmn-js/.npmignore
I accidentally missed that part of the PR.
=> chore(project): exclude coverage reports from packages

packages/dmn-js/CHANGELOG.md
Related to https://github.com/bpmn-io/dmn-js/issues/456
=> chore(CHANGELOG): update to v8.0.0-alpha.0

packages/dmn-js-drd/src/features/modeling/behavior/index.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js, packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js
Related to https://github.com/camunda/camunda-modeler/issues/1679
Requires https://github.com/bpmn-io/dmn-js/pull/461
=> Correctly handle source element id change

packages/dmn-js-drd/src/features/editor-actions/DrdEditorActions.js, packages/dmn-js-drd/test/spec/ModelerSpec.js, packages/dmn-js-drd/test/spec/features/editor-actions/DrdEditorActions.dmn, packages/dmn-js-drd/test/spec/features/editor-actions/DrdEditorActionsSpec.js
Fixed against `7.x` so this ends up in `v7.4`.
=> feat(drd): make align and distribution available as editor action

packages/dmn-js-drd/src/features/modeling/behavior/index.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js, packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js
Closes #467
Related to https://github.com/camunda/camunda-modeler/issues/1679
=> fix(drd/modeling): update connection `href` on source id change

packages/dmn-js-drd/src/features/modeling/ElementFactory.js, packages/dmn-js-drd/test/spec/features/modeling/ElementFactorySpec.js
Related to https://github.com/bpmn-io/dmn-migrate/blob/master/CHANGELOG.md#042.
=> feat(drd): generate semantic ids for DI elements

packages/dmn-js-shared/src/base/Manager.js, packages/dmn-js-shared/test/spec/base/EditingManagerSpec.js, packages/dmn-js-shared/test/spec/base/ManagerSpec.js, packages/dmn-js-shared/test/spec/base/dmn-11.dmn, packages/dmn-js-shared/test/spec/base/dmn-12.dmn, packages/dmn-js/test/spec/ViewerSpec.js, packages/dmn-js/test/spec/dmn-11.dmn
=> Indicate older DMN file incompatibility

package-lock.json, packages/dmn-js-decision-table/src/import/TableTreeWalker.js, packages/dmn-js-decision-table/test/helper/DecisionTableEditor.js, packages/dmn-js-decision-table/test/helper/DecisionTableViewer.js, packages/dmn-js-decision-table/test/spec/features/view-drd/MockViewer.js, packages/dmn-js-decision-table/test/spec/features/view-drd/ViewDrdSpec.js, packages/dmn-js-drd/src/features/drill-down/DrillDown.js, packages/dmn-js-drd/src/features/popup-menu/ReplaceMenuProvider.js, packages/dmn-js-drd/src/features/replace/DrdReplace.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/ReplaceElementBehaviorSpec.js, packages/dmn-js-drd/test/spec/features/popup-menu/ReplaceMenuProviderSpec.js, packages/dmn-js-drd/test/spec/features/replace/DrdReplaceSpec.js, packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesComponent.js, packages/dmn-js-literal-expression/src/features/literal-expression-properties/components/LiteralExpressionPropertiesEditorComponent.js, packages/dmn-js-literal-expression/src/features/modeling/Modeling.js, packages/dmn-js-literal-expression/src/features/textarea/components/TextareaComponent.js, packages/dmn-js-literal-expression/src/features/textarea/components/TextareaEditorComponent.js, packages/dmn-js-literal-expression/test/helper/LiteralExpressionEditor.js, packages/dmn-js-literal-expression/test/helper/LiteralExpressionViewer.js, packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionEditorPropertiesSpec.js, packages/dmn-js-literal-expression/test/spec/features/modeling/ModelingSpec.js, packages/dmn-js-literal-expression/test/spec/features/textarea/TextareaEditorSpec.js, packages/dmn-js-literal-expression/test/spec/features/view-drd/MockViewer.js, packages/dmn-js-literal-expression/test/spec/features/view-drd/ViewDrdSpec.js, packages/dmn-js-shared/package.json, packages/dmn-js/src/Modeler.js, packages/dmn-js/src/Viewer.js
This updates to dmn-moddle@9 which introduces certain adjustments
that better map the model to the actual DMN 1.3 meta-model.
=> Update to dmn-moddle@9

packages/dmn-js-decision-table/src/Editor.js
We import the same module a few lines above
=> chore(decision-table): remove doubled module usage

packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js, packages/dmn-js-decision-table/test/spec/features/editor-actions/EditorActionsSpec.js, packages/dmn-js-decision-table/test/spec/features/keyboard/KeyboardSpec.js, packages/dmn-js-decision-table/test/util/KeyEvents.js
=> feat(decision-table): add new rule on bottom rule <enter>

packages/dmn-js-decision-table/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js, packages/dmn-js-decision-table/test/spec/features/modeling/behavior/two-decision-tables.dmn, packages/dmn-js-drd/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js, packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js
This PR ports https://github.com/bpmn-io/dmn-js/pull/485 to 7.x branch.
=> fix(modeling): update association's refs on element id change

packages/dmn-js-decision-table/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js, packages/dmn-js-decision-table/test/spec/features/modeling/behavior/two-decision-tables.dmn, packages/dmn-js-drd/test/spec/features/modeling/behavior/IdChangeBehaviorSpec.js, packages/dmn-js-shared/src/features/modeling/behavior/IdChangeBehavior.js
=> Update association refs on id change

packages/dmn-js-decision-table/src/Editor.js, packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js, packages/dmn-js-decision-table/test/spec/features/editor-actions/EditorActionsSpec.js, packages/dmn-js-decision-table/test/spec/features/keyboard/KeyboardSpec.js, packages/dmn-js-decision-table/test/util/KeyEvents.js, packages/dmn-js-drd/src/features/label-editing/LabelEditingProvider.js, packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js, packages/dmn-js/CHANGELOG.md
This PR includes following features:
* https://github.com/bpmn-io/dmn-js/pull/482,
* https://github.com/bpmn-io/dmn-js/pull/484,
a changelog update, and a chore PR (https://github.com/bpmn-io/dmn-js/pull/483/commits/87c55cb79540a8ed612930bd888cde9be6c3b09b).
=> Prepare 7.5.0 release

packages/dmn-js-decision-table/src/Editor.js, packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js, packages/dmn-js-decision-table/test/spec/features/editor-actions/EditorActionsSpec.js, packages/dmn-js-decision-table/test/spec/features/keyboard/KeyboardSpec.js, packages/dmn-js-decision-table/test/util/KeyEvents.js, packages/dmn-js-drd/src/features/label-editing/LabelEditingProvider.js, packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js, packages/dmn-js/CHANGELOG.md
This PR includes following features:
* https://github.com/bpmn-io/dmn-js/pull/482,
* https://github.com/bpmn-io/dmn-js/pull/484,
a changelog update, and a chore PR (https://github.com/bpmn-io/dmn-js/pull/483/commits/87c55cb79540a8ed612930bd888cde9be6c3b09b).
=> Release 8 1

packages/dmn-js-drd/package.json, packages/dmn-js-drd/src/Modeler.js, packages/dmn-js-drd/src/draw/DrdRenderer.js, packages/dmn-js-drd/src/draw/TextRenderer.js, packages/dmn-js-drd/src/draw/index.js, packages/dmn-js-drd/src/features/label-editing/LabelEditingProvider.js, packages/dmn-js-drd/src/features/modeling/Modeling.js, packages/dmn-js-drd/src/features/rules/DrdRules.js, packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js, packages/dmn-js-drd/test/spec/features/rules/DrdRulesSpec.js
=> Improve Label Editing

packages/dmn-js-decision-table/src/Viewer.js, packages/dmn-js-decision-table/src/features/cell-selection/CellSelection.js, packages/dmn-js-decision-table/src/features/simple-string-edit/Utils.js, packages/dmn-js-decision-table/test/helper/index.js, packages/dmn-js-decision-table/test/util/KeyEvents.js, packages/dmn-js-drd/src/Modeler.js, packages/dmn-js-drd/src/Viewer.js, packages/dmn-js-drd/src/draw/PathMap.js, packages/dmn-js-drd/src/draw/TextRenderer.js, packages/dmn-js-drd/src/features/context-pad/ContextPadProvider.js, packages/dmn-js-drd/src/features/drill-down/DrillDown.js, packages/dmn-js-drd/src/features/keyboard/DrdKeyboardBindings.js, packages/dmn-js-drd/src/features/label-editing/cmd/UpdateLabelHandler.js, packages/dmn-js-drd/test/helper/index.js, packages/dmn-js-drd/test/util/KeyEvents.js, packages/dmn-js-literal-expression/src/Viewer.js, packages/dmn-js-literal-expression/src/features/editor-actions/EditorActions.js, packages/dmn-js-literal-expression/test/helper/index.js, packages/dmn-js-shared/src/base/Manager.js, packages/dmn-js-shared/src/base/View.js, packages/dmn-js-shared/src/util/DiUtil.js, packages/dmn-js-shared/src/util/IdsUtil.js, packages/dmn-js-shared/src/util/ModelUtil.js
* replace {Boolean} with {boolean}
* replace {Number} with {number}
* replace {String} with {string}
=> chore(documentation): fix JSDoc types

packages/dmn-js-drd/src/Modeler.js, packages/dmn-js-drd/src/features/auto-place/DmnAutoPlace.js, packages/dmn-js-drd/src/features/auto-place/DmnAutoPlaceUtil.js, packages/dmn-js-drd/src/features/auto-place/index.js, packages/dmn-js-drd/src/features/context-pad/ContextPadProvider.js, packages/dmn-js-drd/src/features/label-editing/LabelEditingProvider.js, packages/dmn-js-drd/src/features/modeling/DrdLayouter.js, packages/dmn-js-drd/src/features/modeling/ElementFactory.js, packages/dmn-js-drd/src/features/modeling/behavior/LayoutConnectionBehavior.js, packages/dmn-js-drd/src/features/modeling/behavior/index.js, packages/dmn-js-drd/src/features/snapping/DrdBendpointSnapping.js, packages/dmn-js-drd/src/features/snapping/DrdConnectSnapping.js, packages/dmn-js-drd/src/features/snapping/index.js, packages/dmn-js-drd/test/fixtures/dmn/simple-connections.dmn, packages/dmn-js-drd/test/spec/features/auto-place/DmnAutoPlace.dmn, packages/dmn-js-drd/test/spec/features/auto-place/DmnAutoPlaceSpec.js, packages/dmn-js-drd/test/spec/features/context-pad/ContextPadProviderSpec.js, packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js, packages/dmn-js-drd/test/spec/features/modeling/DrdUpdaterSpec.js, packages/dmn-js-drd/test/spec/features/modeling/ElementFactorySpec.js, packages/dmn-js-drd/test/spec/features/modeling/LayoutConnection.dmn, packages/dmn-js-drd/test/spec/features/modeling/LayoutConnectionSpec.js, packages/dmn-js-drd/test/spec/features/modeling/MoveShapeSpec.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/LayoutConnectionBehaviorSpec.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/layout-connection-behavior.dmn, packages/dmn-js-drd/test/spec/features/snapping/DrdBendpointSnapping.dmn, packages/dmn-js-drd/test/spec/features/snapping/DrdBendpointSnappingSpec.js, packages/dmn-js-drd/test/spec/features/snapping/DrdConnectSnapping.dmn, packages/dmn-js-drd/test/spec/features/snapping/DrdConnectSnappingSpec.js
* connect from new shape to source on append
* add auto-place
* change layout of information requirements
Requires https://github.com/bpmn-io/diagram-js/pull/443
Closes #470
=> Top-Down Modeling

packages/dmn-js-decision-table/package.json, packages/dmn-js-drd/package.json, packages/dmn-js-drd/src/features/auto-place/DmnAutoPlaceUtil.js, packages/dmn-js-literal-expression/package.json, packages/dmn-js-shared/package.json, packages/dmn-js/package.json
Requires https://github.com/bpmn-io/diagram-js/pull/464
=> fix(auto-place): adjust to changed API to fix

packages/dmn-js/CHANGELOG.md
* update CHANGELOG
Related to camunda/camunda-modeler#1776
=> Prepare Release of v8.3.0

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-decision-table/src/features/decision-table-properties/components/DecisionTablePropertiesComponent.js, packages/dmn-js-decision-table/src/features/decision-table-properties/components/DecisionTablePropertiesEditorComponent.js, packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js, packages/dmn-js-decision-table/test/spec/features/cell-selection/CellSelectionSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-properties/DecisionTablePropertiesEditorSpec.js, packages/dmn-js-decision-table/test/spec/features/keyboard/KeyboardSpec.js
=>  feat(decision-table): remove decision id cell

packages/dmn-js-drd/src/features/modeling/DrdUpdater.js
Not required to fix #203 but popped up in the context of investigating that issue.
Related to #203
=> chore(drd/drd-updater): remove redundant waypoints update

packages/dmn-js/rollup.config.js, packages/dmn-js/src/NavigatedViewer.js, packages/dmn-js/tasks/test-distro.js, packages/dmn-js/test/distro/dmn-navigated-viewer.js, packages/dmn-js/test/spec/NavigatedViewerSpec.js
Closes https://github.com/bpmn-io/dmn-js/issues/363
=> feat(dmn-js): expose NavigatedViewer

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/src/features/context-menu/ContextMenu.js, packages/dmn-js-decision-table/src/features/description/Description.js, packages/dmn-js-decision-table/src/features/expression-language/ExpressionLanguage.js, packages/dmn-js-decision-table/test/spec/features/context-menu/ContextMenuSpec.js, packages/dmn-js-decision-table/test/spec/features/expression-language/ExpressionLanguageSpec.js
Reworked context menu.
Closes #495
Requires and includes https://github.com/bpmn-io/dmn-js/pull/511
=> Implement new context menu

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/src/features/allowed-values/components/AllowedValuesEditing.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/InputEditingProvider.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/OutputEditingProvider.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCell.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCellContextMenu.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputCell.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputCellContextMenu.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputEditor.js, packages/dmn-js-decision-table/src/features/type-ref/components/TypeRefCellContextMenu.js, packages/dmn-js-decision-table/test/spec/features/allowed-values/AllowedValuesEditingSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/DecisionTableHeadEditorSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorCellSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/input/InputEditorSpec.js, packages/dmn-js-decision-table/test/spec/features/decision-table-head/editor/output/OutputEditorCellSpec.js, packages/dmn-js-decision-table/test/spec/features/type-ref/TypeRefEditorCellSpec.js, packages/dmn-js-shared/src/components/ContentEditable.js, packages/dmn-js-shared/src/components/List.js, packages/dmn-js-shared/test/spec/components/ContentEditableSpec.js, packages/dmn-js-shared/test/spec/components/ListSpec.js
=> Implement new column header editing component

packages/dmn-js-shared/src/base/Manager.js, packages/dmn-js-shared/test/spec/base/ManagerSpec.js
=> Only fire views.changed on actual change

package-lock.json, packages/dmn-js-decision-table/package.json
This is actually required for the new column editing feature.
=> chore(decision-table): update table-js to v6.1.0

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-shared/src/components/EditableComponent.js, packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js
Closes #533
Described in the issue.
=> 533 center placeholder for empty inputs

package-lock.json, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-decision-table/src/Editor.js, packages/dmn-js-decision-table/src/features/annotations/components/AnnotationHeader.js, packages/dmn-js-decision-table/src/features/column-resize/ColumnResizeProvider.js, packages/dmn-js-decision-table/src/features/column-resize/components/ResizeColumn.js, packages/dmn-js-decision-table/src/features/column-resize/index.js, packages/dmn-js-decision-table/src/features/decision-table-head/components/DecisionTableHead.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCell.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputCell.js, packages/dmn-js-decision-table/src/features/decision-table-properties/DecisionTableProperties.js, packages/dmn-js-decision-table/src/features/decision-table-properties/DecisionTablePropertiesEditor.js, packages/dmn-js-decision-table/src/features/decision-table-properties/components/DecisionTablePropertiesEditorComponent.js, packages/dmn-js-decision-table/src/features/hit-policy/components/HitPolicy.js, packages/dmn-js-decision-table/src/features/hit-policy/editor/components/EditableHitPolicy.js, packages/dmn-js-decision-table/src/features/powered-by/components/PoweredByLogoComponent.js, packages/dmn-js-decision-table/test/TestHelper.js, packages/dmn-js-decision-table/test/spec/features/column-resize/ColumnResizeSpec.js, packages/dmn-js-shared/package.json, packages/dmn-js-shared/src/components/ContentEditable.js, packages/dmn-js-shared/src/components/EditableComponent.js, packages/dmn-js-shared/test/spec/components/EditableComponentSpec.js, packages/dmn-js/test/spec/TabbingSpec.js
Closes #500
In the issue: https://github.com/bpmn-io/dmn-js/issues/500
=> Resizable columns

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
=> fix(decision-table): correctly display bottom border

packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css, packages/dmn-js-literal-expression/src/features/decision-properties/DecisionProperties.js, packages/dmn-js-literal-expression/src/features/decision-properties/DecisionPropertiesEditor.js, packages/dmn-js-literal-expression/src/features/decision-properties/components/DecisionPropertiesComponent.js, packages/dmn-js-literal-expression/src/features/decision-properties/components/DecisionPropertiesEditorComponent.js, packages/dmn-js-literal-expression/src/features/powered-by/components/PoweredByLogoComponent.js, packages/dmn-js-literal-expression/src/features/view-drd/ViewDrd.js, packages/dmn-js-literal-expression/test/spec/features/decision-properties/DecisionPropertiesEditorSpec.js
=> Align literal expression to new design

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
This PR is created to mitigate a problem introduced in https://github.com/bpmn-io/dmn-js/pull/530
Notice how drag rule icon is moved on top of index number.
This PR includes https://github.com/bpmn-io/dmn-js/pull/530
=> Adjust index column width

packages/dmn-js-drd/src/features/label-editing/LabelEditingProvider.js, packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js, packages/dmn-js/CHANGELOG.md
=> Complete label-editing on drillDown.click

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css
Related to https://github.com/camunda/camunda-modeler/issues/1895
=> Correct layout for allowed values

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
=> Fix target indicator for drag and drop

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-drd/assets/css/dmn-js-drd.css, packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css, packages/dmn-js-shared/assets/css/dmn-js-shared.css
=> Align colors with Camunda Modeler

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-decision-table/src/features/column-resize/components/ResizeColumn.js, packages/dmn-js-decision-table/test/spec/features/column-resize/ColumnResizeSpec.js
=> Center the resize hitbox

packages/dmn-js-decision-table/src/features/cell-selection/CellSelection.js, packages/dmn-js-decision-table/test/spec/features/cell-selection/CellSelectionSpec.js
=> Remove unnecessary click event cancel action

packages/dmn-js/CHANGELOG.md
=> chore(CHANGELOG): update to v9.2.0

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
=> Display description indicator within cell

packages/dmn-js-decision-table/src/features/annotations/components/AnnotationCell.js, packages/dmn-js-decision-table/src/features/annotations/editor/components/AnnotationCell.js, packages/dmn-js-decision-table/src/features/context-menu/ContextMenu.js, packages/dmn-js-decision-table/src/features/decision-rule-indices/components/DecisionRuleIndexCellComponent.js, packages/dmn-js-decision-table/src/features/description/Description.js, packages/dmn-js-decision-table/test/spec/features/context-menu/ContextMenuSpec.js, packages/dmn-js-decision-table/test/spec/features/description/DescriptionSpec.js
=> Context menu anywhere on rules

packages/dmn-js-shared/src/base/Manager.js, packages/dmn-js-shared/test/spec/base/ManagerSpec.js
=> fix(shared/Manager): handle return value of event listeners

packages/dmn-js-drd/src/features/modeling/DrdUpdater.js, packages/dmn-js-drd/test/spec/features/modeling/DrdUpdaterSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/1941
=> Update bounds on shape resize

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css
Apply `position: fixed` so that logo is always in bottom-right
corner in literal expression and decision table views. This
requires an empty `transform` so that fixed position is based
on DMN container, cf. https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed
Closes #573
=> Place logo in bottom-right corner

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-decision-table/src/features/decision-table-head/components/DecisionTableHead.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputCell.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/InputEditor.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputCell.js, packages/dmn-js-decision-table/src/features/decision-table-head/editor/components/OutputEditor.js, packages/dmn-js-shared/assets/css/dmn-js-shared.css, packages/dmn-js-shared/src/components/ContentEditable.js, packages/dmn-js-shared/test/spec/components/ContentEditableSpec.js
=> Display input/output placeholders

README.md, packages/dmn-js/README.md
This migrates repo to travis-ci.com.
=> chore(project): migrate to travis-ci.com

tasks/stages/update-examples
This allows to keep `package-lock.json` files updated accordingly.
Related to https://github.com/bpmn-io/dmn-js-examples/issues/18
=> Correctly update examples

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-decision-table/src/features/decision-table-properties/components/DecisionTablePropertiesComponent.js, packages/dmn-js-decision-table/src/features/decision-table-properties/components/DecisionTablePropertiesEditorComponent.js, packages/dmn-js-decision-table/src/features/hit-policy/components/HitPolicy.js, packages/dmn-js-decision-table/src/features/hit-policy/editor/components/EditableHitPolicy.js
=> Allow decision name to take empty space

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
=> fix(styles): fix logo position

.stylelintrc, package-lock.json, package.json, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-drd/assets/css/dmn-js-drd.css, packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css, packages/dmn-js-shared/assets/css/dmn-js-shared.css
Closes #563 
Run `npm run lint-styles` , and, you will see the lint result
=> chore(build): add CSS linting script via stylelint tool

packages/dmn-js-decision-table/src/features/add-rule/AddRule.js, packages/dmn-js-decision-table/src/features/add-rule/components/AddRuleFootComponent.js, packages/dmn-js-decision-table/test/spec/features/add-rule/AddRuleSpec.js
Related to [camunda/camunda-modeler#928](https://github.com/camunda/camunda-modeler/issues/928)
=> Adding a rule now focuses the newly created cell

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-decision-table/src/features/simple-mode/components/SimpleModeButtonComponent.js, packages/dmn-js-decision-table/test/TestHelper.js, packages/dmn-js-decision-table/test/spec/features/simple-mode/SimpleModeSpec.js
Closes #269
Requires https://github.com/bpmn-io/table-js/pull/36
=> feat(decision-table): make first row and column sticky

packages/dmn-js-literal-expression/assets/css/dmn-js-literal-expression.css
Closes #607
Related to camunda/camunda-modeler#2019
=> Fix Literal Expression Styles

package-lock.json, packages/dmn-js-decision-table/package.json, packages/dmn-js-literal-expression/package.json, packages/dmn-js-shared/package.json
=> chore: update to inferno@5.6.1

package-lock.json, packages/dmn-js-decision-table/package.json, packages/dmn-js-literal-expression/package.json, packages/dmn-js-shared/package.json
=> chore: bump inferno version

package-lock.json, package.json, packages/dmn-js-shared/karma.base.js
Related to https://github.com/bpmn-io/internal-docs/issues/240
=> test: use puppeteer provided Chrome

README.md
Related to bpmn-io/internal-docs#196
=> chore(project): add explicit link to code of conduct

packages/dmn-js-decision-table/src/features/context-menu/ContextMenu.js, packages/dmn-js-decision-table/test/spec/features/context-menu/ContextMenuSpec.js
related to https://github.com/camunda/camunda-modeler/issues/2259
=> feat(dmn-table): focus on row added via context menu

README.md, packages/dmn-js-decision-table/test/helper/index.js, packages/dmn-js-decision-table/test/spec/EditorSpec.js, packages/dmn-js-decision-table/test/spec/ViewerSpec.js, packages/dmn-js-decision-table/test/spec/features/view-drd/ViewDrdSpec.js, packages/dmn-js-decision-table/test/spec/import/ImportSpec.js, packages/dmn-js-drd/src/Viewer.js, packages/dmn-js-drd/test/helper/index.js, packages/dmn-js-drd/test/spec/ModelerSpec.js, packages/dmn-js-drd/test/spec/ViewerSpec.js, packages/dmn-js-drd/test/spec/draw/DrdRendererSpec.js, packages/dmn-js-drd/test/spec/import/ImportSpec.js, packages/dmn-js-literal-expression/test/helper/index.js, packages/dmn-js-literal-expression/test/spec/EditorSpec.js, packages/dmn-js-literal-expression/test/spec/ViewerSpec.js, packages/dmn-js-literal-expression/test/spec/features/view-drd/ViewDrdSpec.js, packages/dmn-js-shared/src/base/Manager.js, packages/dmn-js-shared/src/util/CompatibilityUtils.js, packages/dmn-js-shared/test/spec/base/EditingManagerSpec.js, packages/dmn-js-shared/test/spec/base/ManagerSpec.js, packages/dmn-js/test/spec/ModelerSpec.js, packages/dmn-js/test/spec/NavigatedViewerSpec.js, packages/dmn-js/test/spec/ViewerSpec.js
related to #514 
requires bpmn-io/bpmn-js-callbacks-to-promises#2
=> Promisify public apis

packages/dmn-js-shared/src/base/Manager.js, packages/dmn-js/CHANGELOG.md
* Adds changelog
* Gets rid of promise chain
=> Prepare changelog

.github/workflows/POST_RELEASE.yml, tasks/stages/update-demo, tasks/stages/update-examples, tasks/stages/update-website
* enable strict error handling in scripts (https://github.com/bpmn-io/dmn-js/commit/96e409c330b26808ba8110b13f47646d0dfa17b2)
* correct credentials used (https://github.com/bpmn-io/dmn-js/commit/bb0686e8ffcbf40430528225b215b4e8866b2406)
Moving to organization provided credentials, a thing we adopted for `@bpmn-io/form-js` already, too.
---
Closes https://github.com/bpmn-io/dmn-js/issues/645.
=> Improve POST_RELEASE steps

packages/dmn-js-decision-table/src/Viewer.js
Fixed a typo in the source code
=> fix(Viewer): fix typo in viewer.js

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
=> fix(viewer): break long words into multiple lines

.github/workflows/POST_RELEASE.yml, tasks/stages/await-published, tasks/stages/update-demo, tasks/stages/update-examples, tasks/stages/update-website
Pulls in changes implemented via https://github.com/bpmn-io/form-js/pull/174.
---
Closes https://github.com/bpmn-io/dmn-js/issues/658
=> Fix `POST_RELEASE` steps

packages/dmn-js-drd/src/draw/PathMap.js
Related to https://github.com/bpmn-io/bpmn-js/pull/1497
=> fix(path-map): disallow nested tokens

packages/dmn-js-drd/src/features/modeling/behavior/ReplaceElementBehavior.js, packages/dmn-js-drd/test/spec/features/modeling/behavior/ReplaceElementBehaviorSpec.js
Closes camunda/camunda-modeler/issues/2306
https://user-images.githubusercontent.com/25825387/150164290-3af25fe3-8d7d-4c00-9a45-13f5aab4d11b.mov
=> Select new shape after replace

packages/dmn-js-shared/src/features/expression-languages/ExpressionLanguages.js
=> chore: improve jsdoc

packages/dmn-js-drd/test/spec/features/auto-place/DmnAutoPlaceSpec.js, packages/dmn-js-drd/test/spec/features/connection-preview/ConnectionPreviewSpec.js, packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js, packages/dmn-js-drd/test/spec/import/DrdTreeWalkerSpec.js, packages/dmn-js-shared/test/spec/features/expression-languages/ExpressionLanguagesSpec.js, packages/dmn-js/CHANGELOG.md
This updates changelog to v12.0.0.
=> Prepare v12.0.0 release

packages/dmn-js-decision-table/src/features/simple-duration-edit/Utils.js, packages/dmn-js-decision-table/test/spec/features/simple-duration-edit/SimpleDurationEditSpec.js, packages/dmn-js-decision-table/test/spec/features/simple-duration-edit/simple-duration-edit.dmn
=> fix: handle empty duration cells

packages/dmn-js/CHANGELOG.md
=> chore(CHANGELOG): update to v12.0.1

packages/dmn-js-drd/src/draw/DrdRenderer.js, packages/dmn-js-drd/test/spec/draw/DrdRendererSpec.js
=> feat(drd): accept default colors for DRD elements

packages/dmn-js-shared/assets/css/dmn-js-shared.css, packages/dmn-js-shared/src/components/InputSelect.js, packages/dmn-js-shared/test/spec/components/InputSelectSpec.js
https://user-images.githubusercontent.com/28307541/162735393-6d90632f-593c-446c-a3df-8ab7b11e50d0.mov
Related to https://github.com/camunda/camunda-modeler/issues/2908
=> fix: make sure InputSelect options are always accessible

packages/dmn-js-drd/test/spec/import/ImportSpec.js, packages/dmn-js-shared/src/base/Manager.js, packages/dmn-js-shared/test/spec/base/ManagerSpec.js, packages/dmn-js-shared/test/spec/base/drd-only.dmn, packages/dmn-js/src/Modeler.js, packages/dmn-js/test/spec/ViewerSpec.js, packages/dmn-js/test/spec/drd-only.dmn
=> fix: clear state during reimport

packages/dmn-js-drd/src/features/label-editing/LabelEditingProvider.js, packages/dmn-js-drd/test/spec/features/label-editing/LabelEditingProviderSpec.js
=> fix: complete direct editing on selection changed

packages/dmn-js-drd/src/Viewer.js, packages/dmn-js-drd/test/spec/ViewerSpec.js
Regression from the diagram-js@8 upgrade
related to https://github.com/camunda/camunda-modeler/issues/3068
=> fix(drd): fix svg creation

.github/workflows/CI.yml
Attempts to close https://github.com/bpmn-io/dmn-js/issues/672.
=> deps: update to codecov/codecov-action@v3

packages/dmn-js-decision-table/src/features/view-drd/components/ViewDrdComponent.js, packages/dmn-js-literal-expression/src/features/view-drd/components/ViewDrdComponent.js
the default button type is submit, so this button can cause issues inside a form
=> add type=button to view drd button

.github/workflows/CI.yml, .github/workflows/POST_RELEASE.yml, package-lock.json, package.json, packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css
Ensures that all header labels are capped at 3 lines
raised in slack: https://camunda.slack.com/archives/GP70M0J6M/p1675953193428329?thread_ts=1675874910.181129&cid=GP70M0J6M
----
closes https://github.com/bpmn-io/dmn-js/issues/719
=> fix(decision-table): clamp output label

package-lock.json, packages/dmn-js-drd/test/spec/draw/DrdRendererSpec.js, packages/dmn-js/package.json, packages/dmn-js/rollup.config.js, packages/dmn-js/tasks/build-distro.js
Update to rollup@3 and general house keeping.
=> Bump rollup

packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionEditorProperties.no-type-ref.dmn, packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionEditorPropertiesSpec.js, packages/dmn-js-literal-expression/test/spec/features/literal-expression-properties/LiteralExpressionPropertiesSpec.js
Related to https://github.com/bpmn-io/dmn-js/pull/748
=> test(literal-expression): verify missing `variable.typeRef` in editor

.github/workflows/CODE_SCANNING.yml
=> ci: setup code scanning with GH CodeQL

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table-controls.css, packages/dmn-js/CHANGELOG.md
=> Increase line height in decision table cell editor

packages/dmn-js-drd/src/features/context-pad/ContextPadProvider.js
Similar to https://github.com/bpmn-io/bpmn-js/commit/aa158e2d5a7de86b8a388945bbb56f217922f1ae
=> chore(context-pad): user friendly titles

packages/dmn-js/CHANGELOG.md
=> chore(CHANGELOG): update to v15.0.1

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/TASK.md
Ensure they comply with our new formatting.
=> chore: update issue templates

babel.config.json, package-lock.json, package.json, packages/dmn-js-decision-table/.babelrc, packages/dmn-js-literal-expression/.babelrc, packages/dmn-js-shared/.babelrc, packages/dmn-js/rollup.config.js, packages/dmn-js/tasks/build-distro.mjs
=> chore: transpile to supported browsers only

.github/workflows/POST_RELEASE.yml, tasks/stages/await-published
Closes https://github.com/bpmn-io/dmn-js/issues/839
=> fix(POST_RELEASE): properly await publishing

.github/workflows/MERGE_MAIN_TO_DEVELOP.yml
=> ci: use conventional commit message

packages/dmn-js-decision-table/assets/css/dmn-js-decision-table.css, packages/dmn-js-decision-table/src/features/add-rule/components/AddRuleFootComponent.js
https://github.com/bpmn-io/dmn-js/assets/28307541/152f5e0f-f4b7-4d86-8573-e79d37ae221d
Closes #846
=> fix: make add row button focussable

package-lock.json, packages/dmn-js-boxed-expression/package.json, packages/dmn-js-decision-table/package.json, packages/dmn-js-literal-expression/package.json, packages/dmn-js-shared/package.json
https://github.com/bpmn-io/dmn-js/assets/28307541/472735af-a33f-434c-8af5-9f27ffe1bf7f
* deps: update to `@bpmn-io/feel-editor@1.4.0`
* deps: update to `@bpmn-io/dmn-variable-resolver@0.7.0`
Closes #785
Closes #827
=> Add snippet suggestions for BKM

package-lock.json, packages/dmn-js-boxed-expression/package.json, packages/dmn-js-decision-table/package.json, packages/dmn-js-literal-expression/package.json, packages/dmn-js-shared/package.json
Upgrade inferno to version 5.6.3. which includes a backport of a fix for handling events in the shadow dom.
Closes https://github.com/bpmn-io/dmn-js/issues/631, the first item at least ("View DRD" and "+" buttons don't work (nothing happens on click)) 
=> chore: upgrade inferno to 5.6.3

package-lock.json, packages/dmn-js-shared/package.json, packages/dmn-js/CHANGELOG.md
* feat: lint first item access
* deps: update to `@bpmn-io/feel-lint@1.3.0`
This adds first-item rule in the FEEL editor.
=> feat: lint first item access

package-lock.json, packages/dmn-js-shared/package.json, packages/dmn-js/CHANGELOG.md
Related to https://github.com/camunda/camunda-modeler/issues/4342
Feel editor now uses full container height and can focus by clicking anywhere in it, not only on text lines.
- https://github.com/bpmn-io/feel-editor/pull/61
=> deps: update to @bpmn-io/feel-editor@1.8.0

package-lock.json, packages/dmn-js-shared/package.json
Updates to latest FEEL editor to properly complete empty arg built-ins:
Closes https://github.com/bpmn-io/dmn-js/issues/898
=> deps: bump to @bpmn-io/feel-editor@1.9.1

package-lock.json, package.json, packages/dmn-js-boxed-expression/package.json, packages/dmn-js-decision-table/package.json, packages/dmn-js-decision-table/test/spec/features/simple-mode/SimpleModeSpec.js, packages/dmn-js-drd/package.json, packages/dmn-js-literal-expression/package.json, packages/dmn-js-shared/package.json, packages/dmn-js/package.json
Performs standard housekeeping. 
=> Housekeeping

packages/dmn-js-decision-table/src/features/simple-mode/components/SimpleModeButtonComponent.js, packages/dmn-js-decision-table/test/spec/features/simple-mode/SimpleModeSpec.js, packages/dmn-js/CHANGELOG.md
This PR prepares v17.0.1 release:
* updates changelog
* fixes the broken test and removes redundant code (cf. https://github.com/bpmn-io/dmn-js/pull/917#issuecomment-2464661721)
=> Prepare v17.0.1

packages/dmn-js/CHANGELOG.md
Updated CHANGELOG
- Added formal parameters sync PR (https://github.com/bpmn-io/dmn-js/pull/914)
- Other changes are just styling changes 
=> chore(CHANGELOG): update for v17.0.2

.github/workflows/MERGE_MAIN_TO_DEVELOP.yml
Related to https://github.com/bpmn-io/internal-docs/issues/1094
This migrates the slack integration to use the v2 API.
=> ci: migrate to slack action v2

.github/workflows/CI.yml
`ubuntu-20.04` is [no longer supported](https://github.com/actions/runner-images/issues/11101). updating to latest (currently `ubuntu-24.04`). ubuntu > 23 also needs special setup for chrome sandbox included by bpmn-io setup action
=> Fix CI pipeline

.github/workflows/CI.yml, package-lock.json, package.json, packages/dmn-js-shared/package.json, packages/dmn-js/CHANGELOG.md
Related to https://github.com/camunda/camunda-modeler/issues/4743
correct completion of lang-feel snippets ([@bpmn-io/feel-editor#70](https://github.com/bpmn-io/feel-editor/pull/75)) via update to `@bpmn-io/feel-editor@1.10.1`
=> update feel-editor to 1.10.1
